# Jekyll configuration

name: My Tech Blog
description: I tend to forget things I've done or learnt. I figured that the main reason is probably because I don't document things I've done. So from now on, I will try to document all that I've learnt, so that my future self can refer back to these documentations whenever necessary. I hope that at the same time it will also benefit those who are trying to learn the same thing I have learnt.

# Url is currently only used only for the RSS feed in feed.xml
url: http://gohkhoonhiang.github.io
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl: ''

social:
  github: gohkhoonhiang
  stackoverflow: ''
  linkedin: gohkhoonhiang
  instagram: ''
  lastfm: ''
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key:
# Yandex metrika (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: ''
comments: false

permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
