title:            My Tech Blog
description:      I tend to forget things I’ve done or learnt. I figured that the main reason is probably because I don’t document things I’ve done. So from now on, I will try to document all that I’ve learnt, so that my future self can refer back to these documentations whenever necessary. I hope that at the same time it will also benefit those who are trying to learn the same thing I have learnt.
# put your disqus here
disqus_shortname: gohkhoonhiang-github
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: ''

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Home'
    url: '/'
  # - title: 'Fork'
  #   url: 'http://github.com/gohkhoonhiang/neo-hpstr-jekyll-theme'
  # - title: 'Install'
  #   url: '/theme-setup/'
  - title: 'Tags'
    url: '/tags'
  - title: 'Archive'
    url: '/archive'
  - title: 'Projects'
    url: '/projects'
  - title: 'About'
    url: '/about'
  # - title: 'Categories'
  #   url: '/categories'
  #   type: 'categories'
  # - title: 'Favorites'
  #   url: '#'
  #   submenu:
  #     - title: 'Code Highlighter'
  #       url: '/intro/code-highlighting-post/'
  #     - title: 'Sample Post'
  #       url: '/intro/sample-post/'

# Owner/author information
owner:
  name:           Goh Khoon Hiang
  site:           https://gohkhoonhiang.github.io
  avatar:         images/my_avatar.png
  bio:            "I am on my way to becoming a software engineer."
  email:          gohkhoonhiang@gmail.com
  # Twitter nick for use in Twitter cards and follow button.
  twitter: gohkhoonhiang # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  github: gohkhoonhiang

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter: 

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/gohkhoonhiang"
  - title: "linkedin"
    url: "https://sg.linkedin.com/in/gohkhoonhiang"
  # - title: "youtube"
  #   url: "https://www.youtube.com/channel/UCfnSek-9HPWOx5e2pH7VFgg"
# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Singapore
locale:      en_SG
future:      true
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:year/:month/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: true

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6

syntax_highlighter: coderay

syntax_highlighter_opts:
  line_numbers: nil
  line_numbers_start: 1
  tab_width: 4
  bold_every: 10
  css: class

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

# do not include protocol, see https://github.com/sunlightlabs/congress/commit/6426761a671d46df6fc5d2526bdaf506c39d789c
enforce_ssl: gohkhoonhiang.github.io

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
